---
- name: Postgresql
  hosts: all
  become: True

  vars: 
    postgresql_version: "14"
    postgresql_bin_path: "/usr/lib/postgresql/{{ postgresql_version }}/bin"
    postgresql_data_dir: "/var/lib/postgresql/{{ postgresql_version }}/main"
    ansible_ssh_pipelining: true 

  tasks: 
  - block: #=======Block for REDHAT=======
    - name: Install packeges
      yum:
        name: 
          - postgresql
          - postgresql-server
        state: present

    - name: Check if PostgreSQL is instialized
      stat: 
        path: "/var/lib/pgsql/data/pg_hba.conf"
      register: postgres_data

    - name: Initialize PostgreSQL
      shell: "postgresql-setup initdb"
      when: not postgres_data.stat.exists

    - name: Start and enable Service
      service: 
        name: postgresql
        state: started
        enabled: True

    when: ansible_os_family == "RedHat"

  - block: #=======Block for Debian=======
    - name: Install packeges
      apt:
        name: 
          - postgresql
          - postgresql-contrib
          - libpq-dev
          - python3-psycopg2
        state: present
      
    - name: Check if PostgreSQL is instialized
      stat: 
        path: "{{ postgresql_data_dir }}/pg_hba.conf"
      register: postgres_data

    - name: Initialize PostgreSQL
      shell: "{{ postgresql_bin_path }}/initdb -D {{ postgresql_data_dir }}"
      become_user: postgres 
      when: not postgres_data.stat.exists

    - name: Start and enable service
      service: 
        name: postgresql
        state: started
        enabled: true

    when: ansible_os_family == "Debian"