---
- name: Install Nginx and settings Web Server
  hosts: all
  become: yes

  roles:
    #- { role: deploy_nginx_web, when: ansible_system == "Linux" }
    #- deploy_docker
    #- deploy_postgresql
    - postgresql_create_db_user_role_remote-access