---
- name: Restart postgresql Debian
  service:
    name: postgresql
    state: restarted
  when: ansible_os_family == "Debian"

- name: Restart postgresql RedHat
  service:
    name: postgresql
    state: restarted
  when: ansible_os_family == "RedHat"