---
- name: Deploy Zabbix Server in CentOS
  hosts: CentOS 
  become: true

  vars: 
    mysql_login_user: "root"
    mysql_root_password: "P@ssw0rd"
    mysql_create_database: "zabbix"
    mysql_create_user: "zabbix"
    mysql_user_password: "P@ssw0rd"
    destin_folder_centos_mariadb_server_cnf: /etc/my.cnf.d/mariadb-server.cnf
    destin_folder_import_db_zabbix: /usr/share/doc/zabbix-server-mysql/create.sql
    destin_folder_php_ini: /etc/php.ini
    destin_folder_nginx_conf: /etc/nginx/nginx.conf
    destin_dolder_zabbix_server_conf: /etc/zabbix/zabbix_server.conf    

  tasks:
    - name: Configure Firewalld
      firewalld:
        port: "{{ item }}"
        permanent: true
        state: enabled
      loop: 
        - "80/tcp"
        - "443/tcp"
        - "10051/tcp"
        - "10050/tcp"
        - "10051/udp"
        - "10050/udp"
        - "3306/tcp"
      notify: 
        - Restart Firewalld

    - name: Disable SELinux
      selinux:
        state: disabled

    - name: Install packeges for MariaDB
      yum: 
        name: 
          - mariadb-server
          - python3-PyMySQL
        state: latest
      notify:
        - Start MariaDB for CentOS

    - name: Configurations root password for MariaDB for CentOS
      mysql_user:
        check_implicit_admin: true
        login_user: "{{ mysql_login_user }}" 
        login_password: "{{ mysql_root_password }}"
        user: root 
        password: "{{ mysql_root_password }}"
        host: localhost

    - name: Install Nginx
      yum: 
        name: nginx 
        state: latest

    - name: Install php
      yum:
        name: 
          - php
          - php-fpm
          - php-mysqli
        state: latest

    - name: Generate php.ini file 
      template: src=php.ini.j2 dest={{ destin_folder_php_ini }}
      notify: 
        - Start and Enable php-fpm

    - name: Generate nginx.conf file  
      template: src=nginx.conf.j2 dest={{ destin_folder_nginx_conf }}
      notify:
        - Start and Enable Nginx

    - name: Install the Zabbix rpm from a remote repo
      dnf: 
        name: 'https://repo.zabbix.com/zabbix/5.0/rhel/8/x86_64/zabbix-release-5.0-1.el8.noarch.rpm'
        state: present

    - name: Install packeges for Zabbix-Server
      yum: 
        name: 
          - zabbix-server-mysql 
          - zabbix-web-mysql
          - zabbix-agent
          - zabbix-get 
        state: latest 

    - name: Generate mariadb-server.cnf file for CentOS
      template: src=mariadb-server.cnf.j2 dest={{ destin_folder_centos_mariadb_server_cnf }}
      notify: 
        - Restart MariaDB for CentOS

    - name: Extract create.sql.gz
      command: bash -c "gunzip /usr/share/doc/zabbix-server-mysql/create.sql.gz"
      ignore_errors: yes

    - name: Create DB for Zabbix
      community.mysql.mysql_db:
        name: "{{ mysql_create_database }}"
        encoding: utf8
        collation: utf8_bin
        target: "{{ destin_folder_import_db_zabbix }}"
        state: import
        login_user: "{{ mysql_login_user }}" 
        login_password: "{{ mysql_root_password }}"
      failed_when: false 

    - name: Create User for Zabbix
      community.mysql.mysql_user:
        name: "{{ mysql_create_user }}"
        password: "{{ mysql_user_password }}"
        priv: '*.*:ALL,GRANT'
        host: '%'
        state: present
        login_user: "{{ mysql_login_user }}"
        login_password: "{{ mysql_root_password }}"

    - name: Generate zabbix_server.conf file 
      template: src=zabbix_server.conf.j2 dest={{ destin_dolder_zabbix_server_conf }}
      notify:
        - Start and Enable Zabbix-Server


  handlers:
    - name: Restart Firewalld
      service:
        name: firewalld  
        state: restarted

    - name: Start MariaDB for CentOS
      service: 
        name: mariadb
        enabled: true 
        state: started

    - name: Restart MariaDB for CentOS
      service: 
        name: mariadb
        state: restarted

    - name: Start and Enable Nginx
      service: 
        name: nginx 
        enabled: true
        state: restarted

    - name: Start and Enable php-fpm
      service: 
        name: php-fpm
        enabled: true
        state: started
    
    - name: Start and Enable Zabbix-Server
      service:
        name: zabbix-server
        enabled: true 
        state: restarted

